module.exports = {
  statusCode: 200,
  body: '{"businesses": [{"id": "QKkVeP0eSJvpPqoKLY-d2A", "alias": "la-trattoria-da-gino-e-gabi-cannero-riviera", "name": "La Trattoria da Gino & Gabi", "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/MNVTcCD5zQKBeq89Ru4FYQ/o.jpg", "is_closed": false, "url": "https://www.yelp.com/biz/la-trattoria-da-gino-e-gabi-cannero-riviera?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA", "review_count": 3, "categories": [{"alias": "italian", "title": "Italian"}], "rating": 4.5, "coordinates": {"latitude": 46.0222702, "longitude": 8.6819801}, "transactions": [], "location": {"address1": "Via Dante 12", "address2": "", "address3": "", "city": "Cannero Riviera", "zip_code": "28821", "country": "IT", "state": "VB", "display_address": ["Via Dante 12", "28821 Cannero Riviera", "Italy"]}, "phone": "+390323788160", "display_phone": "+39 0323 788160", "distance": 209.82254578223575}, {"id": "BYMGoTExC8EWzcfI-MhjSQ", "alias": "ristorante-sano-banano-cannero-riviera", "name": "Ristorante Sano Banano", "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/yXe7gnMXdbIoWTk2k7hFNQ/o.jpg", "is_closed": false, "url": "https://www.yelp.com/biz/ristorante-sano-banano-cannero-riviera?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA", "review_count": 8, "categories": [{"alias": "pizza", "title": "Pizza"}], "rating": 3.5, "coordinates": {"latitude": 46.0221552902986, "longitude": 8.68469963293803}, "transactions": [], "price": "\\u20ac\\u20ac", "location": {"address1": "Via Guglielmo Marconi 30", "address2": null, "address3": null, "city": "Cannero Riviera", "zip_code": "28821", "country": "IT", "state": "AG", "display_address": ["Via Guglielmo Marconi 30", "28821 Cannero Riviera", "Italy"]}, "phone": "+390323788184", "display_phone": "+39 0323 788184", "distance": 417.27159128278254}, {"id": "Fi2jWEEyGZwT5pXeH1EC5w", "alias": "trattoria-giardino-cannero-riviera", "name": "Trattoria Giardino", "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/0FeM7gmICAQ-g24VVCgq7A/o.jpg", "is_closed": false, "url": "https://www.yelp.com/biz/trattoria-giardino-cannero-riviera?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA", "review_count": 6, "categories": [{"alias": "italian", "title": "Italian"}], "rating": 4.0, "coordinates": {"latitude": 46.02284, "longitude": 8.684}, "transactions": [], "location": {"address1": "Via Massimo D\'azeglio 33", "address2": null, "address3": null, "city": "Cannero Riviera", "zip_code": "28821", "country": "IT", "state": "VB", "display_address": ["Via Massimo D\'azeglio 33", "28821 Cannero Riviera", "Italy"]}, "phone": "+390323787138", "display_phone": "+39 0323 787138", "distance": 358.84426623406546}, {"id": "WT66wLEVKEphzDSRHy66dw", "alias": "arancio-amaro-cannero-riviera", "name": "Arancio Amaro", "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/pQwg_ntUtKAqbzRVTEe-Bw/o.jpg", "is_closed": false, "url": "https://www.yelp.com/biz/arancio-amaro-cannero-riviera?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA", "review_count": 2, "categories": [{"alias": "italian", "title": "Italian"}], "rating": 5.0, "coordinates": {"latitude": 46.0198312550874, "longitude": 8.68368454277515}, "transactions": [], "location": {"address1": "Via Magnolie 15", "address2": "", "address3": null, "city": "Cannero Riviera", "zip_code": "28821", "country": "IT", "state": "VB", "display_address": ["Via Magnolie 15", "28821 Cannero Riviera", "Italy"]}, "phone": "+390323788398", "display_phone": "+39 0323 788398", "distance": 415.65282433074594}, {"id": "7EPfPam8yBaCjkwJ6-ElcQ", "alias": "il-cortile-cannero-riviera-2", "name": "Il Cortile", "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/IxgU8jm2a6zruTVh6NOMbw/o.jpg", "is_closed": false, "url": "https://www.yelp.com/biz/il-cortile-cannero-riviera-2?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA", "review_count": 1, "categories": [{"alias": "restaurants", "title": "Restaurants"}, {"alias": "hotels", "title": "Hotels"}], "rating": 5.0, "coordinates": {"latitude": 46.0226241, "longitude": 8.6852009}, "transactions": [], "price": "\\u20ac", "location": {"address1": "Via Massimo D Azeglio 73", "address2": null, "address3": null, "city": "Cannero Riviera", "zip_code": "28821", "country": "IT", "state": "VB", "display_address": ["Via Massimo D Azeglio 73", "28821 Cannero Riviera", "Italy"]}, "phone": "+390323787213", "display_phone": "+39 0323 787213", "distance": 460.87058611391666}, {"id": "YOyv2y03us7gLajNJRa6HA", "alias": "ristorante-europa-cannero-riviera", "name": "Ristorante Europa", "image_url": "", "is_closed": false, "url": "https://www.yelp.com/biz/ristorante-europa-cannero-riviera?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA", "review_count": 4, "categories": [{"alias": "restaurants", "title": "Restaurants"}], "rating": 4.0, "coordinates": {"latitude": 46.021788, "longitude": 8.68553}, "transactions": [], "price": "\\u20ac\\u20ac\\u20ac", "location": {"address1": "Via Magnolie 51", "address2": null, "address3": null, "city": "Cannero Riviera", "zip_code": "28821", "country": "IT", "state": "21", "display_address": ["Via Magnolie 51", "28821 Cannero Riviera", "Italy"]}, "phone": "+390323788292", "display_phone": "+39 0323 788292", "distance": 481.60697280525784}, {"id": "jAvaAotIUIgEiYjEnYATOw", "alias": "hotel-la-rondinella-cannero-riviera-2", "name": "Hotel La Rondinella", "image_url": "", "is_closed": false, "url": "https://www.yelp.com/biz/hotel-la-rondinella-cannero-riviera-2?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA", "review_count": 1, "categories": [{"alias": "italian", "title": "Italian"}], "rating": 5.0, "coordinates": {"latitude": 46.0189, "longitude": 8.6725}, "transactions": [], "location": {"address1": "Via Sacchetti 50", "address2": null, "address3": null, "city": "Cannero Riviera", "zip_code": "28821", "country": "IT", "state": "VB", "display_address": ["Via Sacchetti 50", "28821 Cannero Riviera", "Italy"]}, "phone": "+390323788098", "display_phone": "+39 0323 788098", "distance": 628.0944534900545}, {"id": "2ifBv8F29N19LGFlm7NNPg", "alias": "ristorante-usignolo-trarego-viggiona", "name": "Ristorante Usignolo", "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/vDzOCEDtQFhjoL3q09vhEg/o.jpg", "is_closed": false, "url": "https://www.yelp.com/biz/ristorante-usignolo-trarego-viggiona?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA", "review_count": 1, "categories": [{"alias": "italian", "title": "Italian"}], "rating": 5.0, "coordinates": {"latitude": 46.03167, "longitude": 8.68807}, "transactions": [], "location": {"address1": "Via Provinciale 2", "address2": null, "address3": null, "city": "Trarego Viggiona", "zip_code": "28826", "country": "IT", "state": "VB", "display_address": ["Via Provinciale 2", "28826 Trarego Viggiona", "Italy"]}, "phone": "+390323788356", "display_phone": "+39 0323 788356", "distance": 1295.1622830034141}, {"id": "2Yd0NGBL4wGR4BXa3JUrcQ", "alias": "lido-caffe-da-mauro-e-ari-cannero-riviera", "name": "Lido Caffe da Mauro e Ari", "image_url": "", "is_closed": false, "url": "https://www.yelp.com/biz/lido-caffe-da-mauro-e-ari-cannero-riviera?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA", "review_count": 2, "categories": [{"alias": "pizza", "title": "Pizza"}, {"alias": "italian", "title": "Italian"}, {"alias": "beachbars", "title": "Beach Bars"}], "rating": 2.0, "coordinates": {"latitude": 46.0196749917977, "longitude": 8.67935935581977}, "transactions": [], "location": {"address1": "Via Lido 5", "address2": "", "address3": null, "city": "Cannero Riviera", "zip_code": "28821", "country": "IT", "state": "VB", "display_address": ["Via Lido 5", "28821 Cannero Riviera", "Italy"]}, "phone": "+390323788405", "display_phone": "+39 0323 788405", "distance": 258.5694495715575}, {"id": "MBw09612zJCM6seh56pxFg", "alias": "gelateria-gelatiere-cannero-riviera", "name": "Gelateria Gelatiere", "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/1SU0Lo6SOUxSfUfTpLcHSw/o.jpg", "is_closed": false, "url": "https://www.yelp.com/biz/gelateria-gelatiere-cannero-riviera?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA", "review_count": 1, "categories": [{"alias": "icecream", "title": "Ice Cream & Frozen Yogurt"}], "rating": 5.0, "coordinates": {"latitude": 46.022236300488, "longitude": 8.6790167}, "transactions": [], "price": "\\u20ac\\u20ac", "location": {"address1": "Via Massimo D\'Azeglio 39", "address2": "", "address3": "", "city": "Cannero Riviera", "zip_code": "28821", "country": "IT", "state": "VB", "display_address": ["Via Massimo D\'Azeglio 39", "28821 Cannero Riviera", "Italy"]}, "phone": "", "display_phone": "", "distance": 34.18872331525665}, {"id": "4RSrWZ8NzBYMcvBcbB1VJQ", "alias": "magnolia-cannero-riviera", "name": "Magnolia", "image_url": "", "is_closed": false, "url": "https://www.yelp.com/biz/magnolia-cannero-riviera?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA", "review_count": 1, "categories": [{"alias": "restaurants", "title": "Restaurants"}], "rating": 2.0, "coordinates": {"latitude": 46.01958, "longitude": 8.68184}, "transactions": [], "location": {"address1": "Via Lungolago Delle Magnolie, 9", "address2": null, "address3": null, "city": "Cannero Riviera", "zip_code": "28821", "country": "IT", "state": "VB", "display_address": ["Via Lungolago Delle Magnolie, 9", "28821 Cannero Riviera", "Italy"]}, "phone": "+390323788066", "display_phone": "+39 0323 788066", "distance": 332.97750646967944}], "total": 11, "region": {"center": {"longitude": 8.6793, "latitude": 46.022}}}',
  jsonBody: {
    businesses: [
      {
        id: 'QKkVeP0eSJvpPqoKLY-d2A',
        alias: 'la-trattoria-da-gino-e-gabi-cannero-riviera',
        name: 'La Trattoria da Gino & Gabi',
        image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/MNVTcCD5zQKBeq89Ru4FYQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/la-trattoria-da-gino-e-gabi-cannero-riviera?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA',
        review_count: 3,
        categories: [Array],
        rating: 4.5,
        coordinates: [Object],
        transactions: [],
        location: [Object],
        phone: '+390323788160',
        display_phone: '+39 0323 788160',
        distance: 209.82254578223575
      },
      {
        id: 'BYMGoTExC8EWzcfI-MhjSQ',
        alias: 'ristorante-sano-banano-cannero-riviera',
        name: 'Ristorante Sano Banano',
        image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/yXe7gnMXdbIoWTk2k7hFNQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/ristorante-sano-banano-cannero-riviera?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA',
        review_count: 8,
        categories: [Array],
        rating: 3.5,
        coordinates: [Object],
        transactions: [],
        price: '€€',
        location: [Object],
        phone: '+390323788184',
        display_phone: '+39 0323 788184',
        distance: 417.27159128278254
      },
      {
        id: 'Fi2jWEEyGZwT5pXeH1EC5w',
        alias: 'trattoria-giardino-cannero-riviera',
        name: 'Trattoria Giardino',
        image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/0FeM7gmICAQ-g24VVCgq7A/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/trattoria-giardino-cannero-riviera?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA',
        review_count: 6,
        categories: [Array],
        rating: 4,
        coordinates: [Object],
        transactions: [],
        location: [Object],
        phone: '+390323787138',
        display_phone: '+39 0323 787138',
        distance: 358.84426623406546
      },
      {
        id: 'WT66wLEVKEphzDSRHy66dw',
        alias: 'arancio-amaro-cannero-riviera',
        name: 'Arancio Amaro',
        image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/pQwg_ntUtKAqbzRVTEe-Bw/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/arancio-amaro-cannero-riviera?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA',
        review_count: 2,
        categories: [Array],
        rating: 5,
        coordinates: [Object],
        transactions: [],
        location: [Object],
        phone: '+390323788398',
        display_phone: '+39 0323 788398',
        distance: 415.65282433074594
      },
      {
        id: '7EPfPam8yBaCjkwJ6-ElcQ',
        alias: 'il-cortile-cannero-riviera-2',
        name: 'Il Cortile',
        image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/IxgU8jm2a6zruTVh6NOMbw/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/il-cortile-cannero-riviera-2?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA',
        review_count: 1,
        categories: [Array],
        rating: 5,
        coordinates: [Object],
        transactions: [],
        price: '€',
        location: [Object],
        phone: '+390323787213',
        display_phone: '+39 0323 787213',
        distance: 460.87058611391666
      },
      {
        id: 'YOyv2y03us7gLajNJRa6HA',
        alias: 'ristorante-europa-cannero-riviera',
        name: 'Ristorante Europa',
        image_url: '',
        is_closed: false,
        url: 'https://www.yelp.com/biz/ristorante-europa-cannero-riviera?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA',
        review_count: 4,
        categories: [Array],
        rating: 4,
        coordinates: [Object],
        transactions: [],
        price: '€€€',
        location: [Object],
        phone: '+390323788292',
        display_phone: '+39 0323 788292',
        distance: 481.60697280525784
      },
      {
        id: 'jAvaAotIUIgEiYjEnYATOw',
        alias: 'hotel-la-rondinella-cannero-riviera-2',
        name: 'Hotel La Rondinella',
        image_url: '',
        is_closed: false,
        url: 'https://www.yelp.com/biz/hotel-la-rondinella-cannero-riviera-2?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA',
        review_count: 1,
        categories: [Array],
        rating: 5,
        coordinates: [Object],
        transactions: [],
        location: [Object],
        phone: '+390323788098',
        display_phone: '+39 0323 788098',
        distance: 628.0944534900545
      },
      {
        id: '2ifBv8F29N19LGFlm7NNPg',
        alias: 'ristorante-usignolo-trarego-viggiona',
        name: 'Ristorante Usignolo',
        image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/vDzOCEDtQFhjoL3q09vhEg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/ristorante-usignolo-trarego-viggiona?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA',
        review_count: 1,
        categories: [Array],
        rating: 5,
        coordinates: [Object],
        transactions: [],
        location: [Object],
        phone: '+390323788356',
        display_phone: '+39 0323 788356',
        distance: 1295.1622830034141
      },
      {
        id: '2Yd0NGBL4wGR4BXa3JUrcQ',
        alias: 'lido-caffe-da-mauro-e-ari-cannero-riviera',
        name: 'Lido Caffe da Mauro e Ari',
        image_url: '',
        is_closed: false,
        url: 'https://www.yelp.com/biz/lido-caffe-da-mauro-e-ari-cannero-riviera?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA',
        review_count: 2,
        categories: [Array],
        rating: 2,
        coordinates: [Object],
        transactions: [],
        location: [Object],
        phone: '+390323788405',
        display_phone: '+39 0323 788405',
        distance: 258.5694495715575
      },
      {
        id: 'MBw09612zJCM6seh56pxFg',
        alias: 'gelateria-gelatiere-cannero-riviera',
        name: 'Gelateria Gelatiere',
        image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/1SU0Lo6SOUxSfUfTpLcHSw/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/gelateria-gelatiere-cannero-riviera?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA',
        review_count: 1,
        categories: [Array],
        rating: 5,
        coordinates: [Object],
        transactions: [],
        price: '€€',
        location: [Object],
        phone: '',
        display_phone: '',
        distance: 34.18872331525665
      },
      {
        id: '4RSrWZ8NzBYMcvBcbB1VJQ',
        alias: 'magnolia-cannero-riviera',
        name: 'Magnolia',
        image_url: '',
        is_closed: false,
        url: 'https://www.yelp.com/biz/magnolia-cannero-riviera?adjust_creative=1NqWEY6v4eRFIifCnjnNzA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=1NqWEY6v4eRFIifCnjnNzA',
        review_count: 1,
        categories: [Array],
        rating: 2,
        coordinates: [Object],
        transactions: [],
        location: [Object],
        phone: '+390323788066',
        display_phone: '+39 0323 788066',
        distance: 332.97750646967944
      }
    ],
    total: 11,
    region: { center: { longitude: 8.6793, latitude: 46.022 } }
  }
}
